name: Validate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  swift:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Validate repository
        run: ./scripts/validate_repository.sh
